"""Unit tests for :mod:`etw_analyzer.parsing.packet_decode`.

Synthetic, hex-string fixtures only. No real captures, no scapy. The hex
strings were generated by building the packet with ``struct`` and
``socket.inet_pton``; the comments next to each fixture document the layer
values so future readers can sanity-check the decoder without running the
generator.
"""

from __future__ import annotations

from etw_analyzer.parsing.packet_decode import decode_packet_headers


# Ethernet (dst aa:bb:cc:dd:ee:ff, src 11:22:33:44:55:66, ethertype 0x0800)
# + IPv4 (src 10.0.0.1, dst 10.0.0.2, proto=TCP, id=0xabcd, ttl=64,
#          total_length=40, IHL=5)
# + TCP (src=1234, dst=80, seq=1000, ack=0, data_offset=5, flags=SYN,
#          window=8192)
_IPV4_TCP_SYN_HEX = (
    "aabbccddeeff112233445566"            # eth dst+src
    "0800"                                  # ethertype IPv4
    "4500002800000000400600000a0000010a000002"  # IPv4 header (no options)
                                            # ^ wait, this is the wrong id field - replaced below
)

# Replaced with the actual emitted fixture (id field 0xabcd, ihl=5):
_IPV4_TCP_SYN_HEX = (
    "aabbccddeeff112233445566"
    "0800"
    "4500002800000000400600000a0000010a000002"  # version+ihl=45, tos=00,
                                                  # tot_len=0028 (40), id=0000,
                                                  # flags+frag=0000, ttl=40 (64),
                                                  # proto=06, checksum=0000,
                                                  # src=10.0.0.1, dst=10.0.0.2
    "04d20050000003e8000000005002200000000000"  # src_port=04d2 (1234),
                                                  # dst_port=0050 (80),
                                                  # seq=000003e8 (1000), ack=0,
                                                  # data_off+flags=5002 (SYN),
                                                  # window=2000 (8192), csum=0000,
                                                  # urgptr=0000
)


# Ethernet + IPv4 (src 192.168.1.10, dst 192.168.1.20, proto=UDP, id=0x1234,
#                  ttl=64, total_length=44)
# + UDP (src=5000, dst=5000, length=24) + 16 bytes of zero payload
_IPV4_UDP_HEX = (
    "aabbccddeeff112233445566"
    "0800"
    "4500002c1234000040110000c0a8010ac0a80114"   # IPv4 header, id=0x1234, proto=17
    "13881388001800000000000000000000000000000000000000000000"
)


# Ethernet + IPv6 (src 2001:db8::1, dst 2001:db8::2, next_header=TCP,
#                  hop_limit=64, payload_length=20)
# + TCP (src=4321, dst=443, seq=12345, ack=67890, data_offset=5, flags=ACK,
#         window=65535)
_IPV6_TCP_HEX = (
    "aabbccddeeff11223344556686dd"
    "60000000001406"  # vtcfl=0x60000000, payload_len=20, next_hdr=6 (TCP), hop_limit=...
    "4020010db800000000000000000000000120010db8000000000000000000000002"
    "10e101bb00003039000109325010ffff00000000"
)


# Ethernet + IPv6 + UDP (src=9000, dst=9001, length=8)
_IPV6_UDP_HEX = (
    "aabbccddeeff11223344556686dd"
    "60000000000811"  # vtcfl, payload_len=8, next_hdr=17 (UDP), hop_limit=...
    "4020010db800000000000000000000000120010db8000000000000000000000002"
    "2328232900080000"
)


# Ethernet + ARP request (ethertype 0x0806). No IP / L4 to decode.
_ARP_HEX = (
    "ffffffffffff112233445566"
    "0806"
    "00010800060400011122334455660a0000010000000000000a000002"
)


# Only the first 12 bytes of an Ethernet header — truncated mid-header.
_TRUNCATED_ETH_HEX = "aabbccddeeff112233445566"


# Ethernet + IPv4 but cut off at the IP header (only first 8 bytes of IP).
_TRUNCATED_IP_HEX = (
    "aabbccddeeff112233445566"
    "0800"
    "4500002800000000"  # 8 of 20 IPv4 header bytes
)


def _hex(s: str) -> bytes:
    return bytes.fromhex(s)


class TestEthernet:
    def test_macs_and_ethertype(self):
        d = decode_packet_headers(_hex(_IPV4_TCP_SYN_HEX))
        assert d["eth.dst"] == "aa:bb:cc:dd:ee:ff"
        assert d["eth.src"] == "11:22:33:44:55:66"
        assert d["eth.ethertype"] == 0x0800

    def test_truncated_eth(self):
        d = decode_packet_headers(_hex(_TRUNCATED_ETH_HEX))
        assert d.get("_truncated_at") == "eth"
        # No fields populated because the header didn't fully arrive.
        assert "eth.src" not in d

    def test_empty_bytes(self):
        d = decode_packet_headers(b"")
        assert d.get("_truncated_at") == "eth"


class TestIPv4TCP:
    def test_ipv4_fields(self):
        d = decode_packet_headers(_hex(_IPV4_TCP_SYN_HEX))
        assert d["ip.version"] == 4
        assert d["ip.proto"] == 6
        assert d["ip.src"] == "10.0.0.1"
        assert d["ip.dst"] == "10.0.0.2"
        assert d["ip.ttl"] == 64
        assert d["ip.total_length"] == 40
        assert d["ip.header_len"] == 20

    def test_tcp_fields(self):
        d = decode_packet_headers(_hex(_IPV4_TCP_SYN_HEX))
        assert d["tcp.src_port"] == 1234
        assert d["tcp.dst_port"] == 80
        assert d["tcp.seq"] == 1000
        assert d["tcp.ack"] == 0
        assert d["tcp.data_offset"] == 5
        assert d["tcp.window"] == 8192
        assert d["tcp.flags"] == ["SYN"]
        assert d["tcp.flags_raw"] == 0x02


class TestIPv4UDP:
    def test_ipv4_udp_fields(self):
        d = decode_packet_headers(_hex(_IPV4_UDP_HEX))
        assert d["ip.version"] == 4
        assert d["ip.proto"] == 17
        assert d["ip.src"] == "192.168.1.10"
        assert d["ip.dst"] == "192.168.1.20"
        assert d["ip.id"] == 0x1234
        assert d["udp.src_port"] == 5000
        assert d["udp.dst_port"] == 5000
        assert d["udp.length"] == 24


class TestIPv6:
    def test_ipv6_tcp(self):
        d = decode_packet_headers(_hex(_IPV6_TCP_HEX))
        assert d["ip.version"] == 6
        assert d["ip.proto"] == 6
        assert d["ip.src"] == "2001:db8::1"
        assert d["ip.dst"] == "2001:db8::2"
        assert d["ip.payload_length"] == 20
        assert d["ip.hop_limit"] == 64
        assert d["tcp.src_port"] == 4321
        assert d["tcp.dst_port"] == 443
        assert d["tcp.seq"] == 12345
        assert d["tcp.ack"] == 67890
        assert d["tcp.flags"] == ["ACK"]

    def test_ipv6_udp(self):
        d = decode_packet_headers(_hex(_IPV6_UDP_HEX))
        assert d["ip.version"] == 6
        assert d["ip.proto"] == 17
        assert d["ip.src"] == "2001:db8::1"
        assert d["ip.dst"] == "2001:db8::2"
        assert d["udp.src_port"] == 9000
        assert d["udp.dst_port"] == 9001
        assert d["udp.length"] == 8


class TestARP:
    def test_arp_reports_ethertype_only(self):
        d = decode_packet_headers(_hex(_ARP_HEX))
        assert d["eth.ethertype"] == 0x0806
        # No IP fields, no L4 fields.
        assert "ip.src" not in d
        assert "tcp.src_port" not in d
        assert "udp.src_port" not in d
        # Not a truncation — the layer simply doesn't apply.
        assert "_truncated_at" not in d


class TestTruncation:
    def test_truncated_ip(self):
        d = decode_packet_headers(_hex(_TRUNCATED_IP_HEX))
        # Ethernet still decoded.
        assert d["eth.ethertype"] == 0x0800
        # IP layer truncated.
        assert d.get("_truncated_at") == "ip"
        # No L4 fields.
        assert "tcp.src_port" not in d

    def test_truncated_tcp_payload(self):
        # Take just the eth + IPv4 portion of the SYN packet (54 bytes total,
        # 34 bytes is eth+IPv4 and 10 bytes of TCP).
        truncated_hex = _IPV4_TCP_SYN_HEX[: 2 * (14 + 20 + 10)]
        d = decode_packet_headers(_hex(truncated_hex))
        # IP fields populated, TCP partially decoded then truncated.
        assert d["ip.version"] == 4
        assert d.get("_truncated_at") == "tcp"


def test_ipv4_tcp_hex_length_sanity():
    """Sanity-check fixture sizes match expected Ethernet + IPv4 + TCP."""
    assert len(_hex(_IPV4_TCP_SYN_HEX)) == 14 + 20 + 20
    # UDP fixture is eth + IPv4 + UDP header + 20-byte zero payload.
    assert len(_hex(_IPV4_UDP_HEX)) == 14 + 20 + 8 + 20
