"""FastMCP application instance — imported by all tool modules."""

from mcp.server.fastmcp import FastMCP

mcp = FastMCP(
    "etw-trace-analyzer",
    instructions=(
        "Analyze Windows ETW/WPR traces (.etl files). Workflow is always: "
        "load -> orient -> query -> drill down.\n"
        "\n"
        "LOAD: call `load_trace(etl_path=...)` first; every analysis tool needs "
        "the returned `trace_id`. There is no current-trace state -- pass the id "
        "explicitly on each call so multiple traces can be analyzed in parallel. "
        "`load_trace` walks the fallback chain dotnet -> native -> xperf. The "
        ".NET sidecar wins when `WPR_MCP_CSHARP_SIDECAR` is set or "
        "`wpr-mcp-extract.exe` is on PATH; force a single backend with "
        "`mode='dotnet'|'native'|'xperf'` or the `WPR_MCP_MODE` env var.\n"
        "\n"
        "ORIENT (cheap, run after every load): `list_loaded_traces` for the live "
        "registry, `trace_info`, `get_sysconfig`, then `analyze` for the one-shot "
        "report of hot modules + per-CPU summary + DPC summary + symbol status.\n"
        "\n"
        "QUERY hot CPU: `get_cpu_samples`, `get_per_cpu_summary`, "
        "`get_cpu_timeline`. Hot stacks: `get_hot_functions`, `get_hot_stacks`, "
        "`get_function_callers`, `walk_stack`, `butterfly_chain`, `count_stacks`. "
        "Kernel pressure: `get_dpc_summary`, `get_dpc_per_cpu`, "
        "`get_lock_contention`.\n"
        "\n"
        "QUERY network (these are wrappers over the generic tools with the "
        "networking module set pre-applied, so `tcpip.sys` / `ndis.sys` / "
        "`xdp.sys` / `afd.sys` / NIC drivers / `ws2_32.dll` / `msquic.dll` are "
        "already in scope -- use them instead of remembering module names): "
        "`get_network_hot_functions`, `get_network_hot_stacks`, "
        "`get_network_dpcs`, `get_network_lock_contention`, "
        "`get_network_wait_chain`, `get_rss_dispatch_quality`, "
        "`get_per_nic_queue_arrivals`, `get_udp_dispatch_quality`. "
        "Per-socket / per-flow: `get_per_process_socket_throughput`, "
        "`get_connection_summary`, `get_udp_flow_summary`, "
        "`get_tcp_retransmits`, `get_connect_latency`, `get_accept_latency`, "
        "`get_packet_drops`, `get_afd_batching`, `get_socket_lifecycle`, "
        "`get_socket_affinity_check`. Packet capture (pktmon ETLs): "
        "`get_packet_capture_summary`, `get_packet_timeline`, `decode_packet`, "
        "`get_send_recv_latency`, `get_pktmon_layer_latency`. HTTP/QUIC: "
        "`get_http_requests`, `get_http_queue_depth`, `get_quic_connections`, "
        "`get_quic_cid_distribution`, `get_quic_ack_delays`.\n"
        "\n"
        "SYMBOLS: set `_NT_SYMBOL_PATH` in env. Call `check_symbols` to see what "
        "is unresolved, `resolve_symbols` to force a dbghelp re-download. "
        "Symbol resolution is identical across dotnet / native / xperf.\n"
        "\n"
        "RECOVERY: every error return names the next command. If a tool says "
        "'Trace not found', call `list_loaded_traces` then `load_trace` again "
        "(cache hits are fast). See ARCHITECTURE.md S8 for failure modes."
    ),
)
